language: cpp
compiler: gcc
os: linux
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install chrpath devscripts -y || true
 - sudo apt-get source libsqlite3-0 -y
 - sudo apt-get build-dep libsqlite3-0 -y || true
 - sudo sed -i '/export CFLAGS/a \        -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT=1 \\' sqlite3*/debian/rules
 - sudo sh -c "cd sqlite3* && debuild -b -uc -us"
 - sudo dpkg -i *.deb
 - sudo apt-get remove libboost-all-dev -y
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install libboost1.54-all-dev libcloog-ppl0 -y
 - ls /usr/lib
script:
 - sudo chmod -R 755 * || false
 - sed -i 's/-D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN //g' Makefile || false
 - sed -i 's/ -Wno-maybe-uninitialized//g' Makefile || false
 - make PREFIX= CC=$CC CXX=$CXX LD=$CXX AR=ar UNICODE= "LDFLAGS=-s -Wl,--allow-multiple-definition" "pp_lib=libboost_program_options libboost_locale libboost_filesystem libboost_iostreams libboost_date_time libboost_thread libboost_regex libboost_system libsqlite3 libpthread" || false
 - make PREFIX= CC=$CC CXX=$CXX LD=$CXX AR=ar UNICODE= "LDFLAGS=-s -Wl,--allow-multiple-definition" "pp_lib=libboost_program_options libboost_locale libboost_filesystem libboost_iostreams libboost_date_time libboost_thread libboost_regex libboost_system libsqlite3 libpthread" check || false