language: cpp
compiler: gcc
os: linux
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install libboost-all-dev libsqlite3-dev libcloog-ppl0
script:
 - sudo chmod -R 755 * || exit 1
 - make PREFIX= CC=$CC CXX=$CXX LD=$CXX AR=$CC-ar UNICODE= "LDFLAGS=-s -Wl,--allow-multiple-definition" "pp_lib=libboost_program_options libboost_locale libboost_filesystem libboost_iostreams libboost_date_time libboost_thread libboost_regex libboost_system libsqlite3 libpthread" || exit 1
 - bin/pp.exe --help || exit 1