language: cpp
compiler: gcc
os: linux
before_script:
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install libboost1.54-all-dev libsqlite3-dev libcloog-ppl0 -y
 - ls /usr/lib
script:
 - sudo chmod -R 755 * || exit 1
 - sed -i 's/-D_WIN32_WINNT=0x0501 -DWIN32_LEAN_AND_MEAN //g' Makefile || exit 1
 - sed -i 's/ -Wno-maybe-uninitialized//g' Makefile || exit 1
 - make PREFIX= CC=$CC CXX=$CXX "LD=$CXX -v" AR=ar UNICODE= "LDFLAGS=-s -Wl,--allow-multiple-definition" "pp_lib=libboost_program_options libboost_locale libboost_filesystem libboost_iostreams libboost_date_time libboost_thread libboost_regex libboost_system libsqlite3 libpthread" || exit 1
 - bin/pp.exe --help || exit 1