version: 1.3.1.{build}

install:
 - appveyor DownloadFile https://www.cygwin.com/setup-x86_64.exe -FileName C:\cygwin64\setup-x86_64.exe
#- C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P mingw64-x86_64-clang -P mingw64-x86_64-boost -P mingw64-x86_64-sqlite3
 - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P clang -P libboost-devel -P libsqlite3-devel
 - echo "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\editbin.exe" /STACK:16777216 "C:\cygwin64\bin\clang-3.8.exe" >C:\patch-clang.bat
 - C:\patch-clang.bat

build_script:
 - C:\cygwin64\bin\bash -lc "sed -i -e 's/-fgraphite//g' -e 's/-static/ -D_GNU_SOURCE -U_MSC_VER/g' -e 's/-Wno-maybe-uninitialized/-fexceptions -ftemplate-depth=1024/g' /cygdrive/c/projects/pp/Makefile"
#- C:\cygwin64\bin\bash -lc "sed -i -e 's/\\(libboost_[_0-9a-zA-Z]*\\)/\\1-mt/g' /cygdrive/c/projects/pp/common.mk"
#- C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/pp PREFIX=x86_64-w64-mingw32- CC=clang CXX=clang++ LD=clang++"
 - C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/pp CC=clang CXX=clang++ LD=clang++"

test_script:
 - C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/pp check"
